/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p OfonoSimManager -v ofono.xml org.ofono.SimManager
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "OfonoSimManager.h"

/*
 * Implementation of interface class OrgOfonoSimManagerInterface
 */

OrgOfonoSimManagerInterface::OrgOfonoSimManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgOfonoSimManagerInterface::~OrgOfonoSimManagerInterface()
{
}

